/****** Object:  StoredProcedure [dbo].[GETCONTRACTSUMMARYBYVENDORID]    Script Date: 27-01-2025 11:22:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[GETCONTRACTSUMMARYBYVENDORID] (@VENDORCONTRACTID INT)
AS
BEGIN
SELECT V.VENDOR_ID VENDOR_ID,VC.ISACTIVE VENDOR_ISACTIVE,V.LEGAL_NAME VENDOR_LEGAL_NAME,
VC.CONTRACT_TEMPLATE_ID CONTRACT_TEMPLATE_ID,VC.WORKFLOW_ID WORKFLOW_ID,VC.STATIC_KEY_POINTERS STATIC_KEY_POINTERS,VC.CONTRACT_FILE CONTRACT_FILE,VC.ISACTIVE ISACTIVE,
VC.UPDATED_BY UPDATED_BY,VC.UPDATED_ON UPDATED_ON,VC.SYSSTARTTIME SYSSTARTTIME,VC.SYSENDTIME SYSENDTIME,VC.ISBOARDAPPROVALNEEDED ISBOARDAPPROVALNEEDED,VC.ISPERPETUALCONTRACT ISPERPETUALCONTRACT,
VC.ISSTAMPINGNEEDED ISSTAMPINGNEEDED,VC.ISCOSTAPPROVALNEEDED ISCOSTAPPROVALNEEDED,VC.HASPARENTCONTRACT HASPARENTCONTRACT,VC.PARENT_ID PARENT_ID,
VC.PROCESS_TYPE_ID PROCESS_TYPE_ID,VC.PROJECT_COST PROJECT_COST,VC.CURRENCY_ID CURRENCY_ID,VC.CLONED_VENDOR_ID CLONED_VENDOR_ID,VC.CONTRACT_START_DATE CONTRACT_START_DATE,
VC.CONTRACT_END_DATE CONTRACT_END_DATE,VC.CONTRACT_TYPE CONTRACT_TYPE,VC.PROJECT_ID PROJECT_ID,VC.CURRENCY_ID VENDORCONTRACT_CURRENCY_ID,
VC.COMPANY_ID VENDOR_CONTRACT_COMPANY_ID,VC.CONTRACT_REF_NUMBER CONTRACT_REF_NUMBER,VC.CONTRACT_START_DATE CONTRACT_START_DATE,VC.CONTRACT_END_DATE CONTRACT_END_DATE,
VC.VENDOR_ID VENDOR_CONTRACT_VENDOR_ID,

MC.COMPANY_ID COMPANY_ID,MC.LEGAL_NAME LEGAL_NAME,MC.JURISDICTION JURISDICTION,MC.ISACTIVE ISACTIVE,
CM.CLAUSE_CTMAPPING_ID CLAUSE_CTMAPPING_ID,CM.CLAUSE_CTMAPPING_ID CLAUSE_CTMAPPING_ID,CM.TAGGINGRISK  TAGGINGRISK,
CM.SME_REVIEW_REQUIRED SME_REVIEW_REQUIRED,CM.STATUS STATUS,CM.IS_SME_REVIEW_ROMPLETED IS_SME_REVIEW_ROMPLETED,
CM.SME_USER SME_USER,CM.IS_SME_SIGNED_OFF IS_SME_SIGNED_OFF,CM.SME_SIGNED_OFF_USER SME_SIGNED_OFF_USER,
CM.SME_SIGNED_OFF_TIMESTAMP SME_SIGNED_OFF_TIMESTAMP,CM.IS_DO_REVIEW_COMPLETED IS_DO_REVIEW_COMPLETED,
CM.DO_USER DO_USER,CM.IS_SO_REVIEW_COMPLETED IS_SO_REVIEW_COMPLETED,CM.SO_USER SO_USER,CM.IS_DO_REQUIRED IS_DO_REQUIRED,
CM.CLAUSE_ID CLAUSE_ID,CM.CONTRACT_TEMPLATE_ID CONTRACT_TEMPLATE_ID,
CM.ISACTIVE ISACTIVE,VC.VENDOR_CONTRACT_ID VENDOR_CONTRACT_ID,MCY.SYMBOL  SYMBOL,
SM.VC_SERVICEMAPPING_ID VC_SERVICEMAPPING_ID,SM.VENDOR_CONTRACT_ID SERVICEMAPPING_VENDOR_CONTRACT_ID,
VC.VENDOR_CONTRACT_ID VENDOR_CONTRACT_ID,VC.COMPANY_ID COMPANY_ID,
MCY.SYMBOL CURRENCY_SYMBOL,MCY.CURRENCY_ID CURRENCY_ID,MCY.CURRENCY_CODE CURRENCY_CODE,MCY.CURRENCY_NAME CURRENCY_NAME,
SC.SERVICECATALOG_ID SERVICECATALOG_ID,SC.SERVICE_NAME SERVICE_NAME,SC.SERVICE_DESCRIPTION SERVICE_DESCRIPTION,

CLM.CLAUSE_HEADER,CLM.CLAUSE,CLM.CLAUSE_CONTRACT_HEADER

FROM DBO.TBLVMVENDORS V
INNER JOIN DBO.TBLCMVENDORCONTRACT VC ON V.VENDOR_ID=VC.VENDOR_ID
INNER JOIN DBO.TBLCMCLAUSECTMAPPING CM ON CM.CONTRACT_TEMPLATE_ID=VC.CONTRACT_TEMPLATE_ID
INNER JOIN DBO.TBLCMVCSERVICEMAPPING SM ON VC.VENDOR_CONTRACT_ID=SM.VENDOR_CONTRACT_ID
INNER JOIN DBO.TBLVMMASTERSERVICESCATALOG SC ON SC.SERVICECATALOG_ID=SM.SERVICECATALOG_ID
INNER JOIN DBO.TBLMASTERCOMPANY MC ON MC.COMPANY_ID=VC.COMPANY_ID
LEFT JOIN DBO.TBLMASTERCURRENCY MCY ON MCY.CURRENCY_ID=VC.CURRENCY_ID
INNER JOIN DBO.TBLCMCLAUSEMASTER CLM ON CLM.CLAUSE_ID=CM.CLAUSE_ID
WHERE VC.VENDOR_CONTRACT_ID=@VENDORCONTRACTID
END
